name: Reusable Deployment Workflow
on:
  workflow_call:
    inputs:
      text1:
        required: true
        type: string
      text2:
        required: true
        type: string

    secrets:
      slack_token:
        required: true

env:
  SLACK_TOKEN: ${{ secrets.slack_token }}
  TEXT1: ${{ inputs.text1 }}
  TEXT2: ${{ inputs.text2 }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: print message
        run: |
          echo "the text1 content is $TEXT1"
          echo "the text2 content is $TEXT2"

      - name: New Branch Slack notification
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: 'reuse workflow test'
          message_format: 'Text1 is ${{ env.TEXT1 }} and the text2 is ${{ env.TEXT2 }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_token }}