name: Production PR Workflow
on:
  workflow_call:
    secrets:
      temp_github_token:
        required: true

env:
  from_branch: ${{ github.event.pull_request.head.ref }}
  to_branch: ${{ github.event.pull_request.base.ref }}
  repo_name: ${{ github.event.repository.name }}

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Production Deployment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.temp_github_token }}
          fetch-depth: 0

      - name: Production Deployment
        id: prod_deploy
        run: |
          echo "Prod deployment"

      - name: Delete Feature Branch
        if: steps.prod_deploy.outcome == 'success'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.temp_github_token }}
          branches: ${{ github.event.pull_request.head.ref }}

      - name: Delete Feature Branch's Tags in Github
        if: steps.prod_deploy.outcome == 'success'
        run: |
          git remote set-url origin https://${{ secrets.G_TOKEN }}@github.com/CondeNast/${{ env.repo_name }}.git
          git fetch --all
          from_branch_name=`echo "${from_branch}"`
          to_branch_name=`echo "${to_branch}"`
          git switch -c ${{ github.event.pull_request.head.ref }} origin/tstg
          git pull origin ${{ github.event.pull_request.head.ref }} --tags
          tag_list=`git tag --sort version:refname | grep "$from_branch_name"`
          for tags in $tag_list; do
            echo "The tag $tags is deleted successfully"
            git push --delete origin $tags
          done